## 01실습

다음의 ages를 bins의 구간으로 나누어 보세요. (hint. pd.cut()을 사용하세요.)
```
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

```


In [ ]:
import pandas as pd

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

pd.cut(ages, bins)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

# 02실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [ ]:
import numpy as np
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data의 합계와 fish_data의 사이즈를 구하시오. (np.sum(), len()) 

In [ ]:
np.sum(fish_data), len(fish_data)

(40, 10)

2. fish_data 의 평균을 구하시오.

In [ ]:
np.sum(fish_data)/len(fish_data), np.mean(fish_data)

(4.0, 4.0)

3. fish_data의 중위수(중앙값)을 구하시오.

In [ ]:
np.median(fish_data)

4.0

4. fish_data 의 최빈값을 구하시오.

In [ ]:
from scipy import stats
stats.mode(fish_data)

ModeResult(mode=array([4]), count=array([4]))

In [ ]:
pd.Series(fish_data).mode()

0    4
dtype: int32

# 03실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [ ]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data 의 분산을 구하시오

In [ ]:
fish_data.var()

1.2

2. fish_data의 불편분산을 구하시오.

In [ ]:
fish_data.var(ddof=1)

1.3333333333333333

3. fish_data의 표준편차를 구하시오.

In [ ]:
fish_data.std()

1.0954451150103321

4. fish_data의 사분위수를 구하시오.

In [ ]:
Q1,Q2,Q3 = np.percentile(fish_data, [0.25, 0.5, 0.75])
print(Q1, Q2, Q3)

2.0225 2.045 2.0675


5. fish_data의 IQR값을 구하시오.

In [ ]:
IQR = Q3 - Q1
IQR

0.04499999999999993

# 04실습 

다음과 같이 물고기의 크기와 무게에 관련된 데이터가 있다.

```
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data
```

In [ ]:
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data

length  weight
0    18.5      34
1    18.7      39
2    19.1      41
3    19.7      38
4    21.5      45
5    21.7      41
6    21.8      52
7    22.0      44
8    23.4      44
9    23.8      49

1. 물고기 데이터에서 length와 weight 간의 공분산을 구하시오.

In [ ]:
np.cov(data.length, data.weight)

array([[ 3.64622222,  7.67333333],
       [ 7.67333333, 28.01111111]])

In [ ]:
data.cov()

length     weight
length  3.646222   7.673333
weight  7.673333  28.011111

2. 물고기 데이터에서  length와 weight 간의 상관계수를 구하시오.

In [ ]:
np.corrcoef(data.length, data.weight)

array([[1.       , 0.7592719],
       [0.7592719, 1.       ]])

In [ ]:
data.corr()

length    weight
length  1.000000  0.759272
weight  0.759272  1.000000

# 06.실습



1. 10개의 제비중에 4개의 당첨 제비가 포함되어 있다. 이 중 3개의 제비를 임의로 뽑을 때 다음을 구하시오.

    1) 3개 모두가 당첨 제비가 아닐 확률은?  
    2) 적어도 1개 이상이 제비일 확률은?

In [1]:
from itertools import combinations

lottery = list(combinations([1,1,1,1,0,0,0,0,0,0], 3))
N = len(list(lottery))

In [3]:
wins = 0

for i in lottery:
    if (i.count(0) == 3):
        wins += 1

print('3개 모두가 당첨 제비가 아닐 확률 = ', wins/N)

3개 모두가 당첨 제비가 아닐 확률 =  0.16666666666666666


In [4]:
wins = 0

for i in lottery:
    if (i.count(1) == 1) or (i.count(1) == 2) or (i.count(1) == 3):
        wins += 1

print('적어도 1개 이상이 제비일 확률 = ', wins/N)

적어도 1개 이상이 제비일 확률 =  0.8333333333333334


In [5]:
1-(20/120)

0.8333333333333334

# 10실습

1. 복권의 당첨률이 30% 라고 한다. 복권을 8장 구입했다. 이항분포로 다음의 확률을 구하시오.
    - 4장이 당첨될 확률은? ($P=4$)
    - 3장에서 7장 당첨될 확률은? ( $P(3\le X \le 7$ )
    - 6장 이상 당첨될 확률은? ( $P \ge 6$ )

In [ ]:
rv = stats.binom(8, 0.3)
rv.pmf(4), rv.cdf(7)-rv.cdf(2), 1-rv.cdf(5)

(0.1361367, 0.44816058000000014, 0.011292210000000025)

# 11실습

1. 확률변수 X가 평균이 70, 표준편차가 10인 정규분포를 따를때 다음의 확률을 구하시오.
    
    - P(X < 94.3)
    - P(X > 57.5)
    - P(57.7 < X < 94.3)

In [ ]:
rv = stats.norm(loc = 70, scale=10)

rv.cdf(94.3), 1-rv.cdf(57.5), rv.cdf(94.3)-rv.cdf(57.5)

(0.9924505885836908, 0.8943502263331446, 0.8868008149168355)