## 01실습

다음의 ages를 bins의 구간으로 나누어 보세요. (hint. pd.cut()을 사용하세요.)
```
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

```


In [7]:
import pandas as pd

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

pd.cut(ages, bins)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

# 02실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [9]:
import numpy as np
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data의 합계와 fish_data의 사이즈를 구하시오. (np.sum(), len()) 

In [10]:
np.sum(fish_data), len(fish_data)

(40, 10)

2. fish_data 의 평균을 구하시오.

In [11]:
np.sum(fish_data)/len(fish_data), np.mean(fish_data)

(4.0, 4.0)

3. fish_data의 중위수(중앙값)을 구하시오.

In [12]:
np.median(fish_data)

4.0

4. fish_data 의 최빈값을 구하시오.

In [19]:
from scipy import stats
stats.mode(fish_data)

ModeResult(mode=array([4]), count=array([4]))

In [20]:
pd.Series(fish_data).mode()

0    4
dtype: int32

# 03실습

다음과 같은 물고기의 크기와 관련된 데이터가 있다. 

```
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data
```



In [21]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

1. fish_data 의 분산을 구하시오

In [22]:
fish_data.var()

1.2

2. fish_data의 불편분산을 구하시오.

In [23]:
fish_data.var(ddof=1)

1.3333333333333333

3. fish_data의 표준편차를 구하시오.

In [24]:
fish_data.std()

1.0954451150103321

4. fish_data의 사분위수를 구하시오.

In [32]:
Q1,Q2,Q3 = np.percentile(fish_data, [0.25, 0.5, 0.75])
print(Q1, Q2, Q3)

2.0225 2.045 2.0675


5. fish_data의 IQR값을 구하시오.

In [33]:
IQR = Q3 - Q1
IQR

0.04499999999999993

# 04실습 

다음과 같이 물고기의 크기와 무게에 관련된 데이터가 있다.

```
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data
```

In [42]:
data = pd.DataFrame({'length':[18.5, 18.7, 19.1, 19.7, 21.5, 21.7, 21.8, 22. , 23.4, 23.8], 
                     'weight':[34, 39, 41, 38, 45, 41, 52, 44, 44, 49]})
data

length  weight
0    18.5      34
1    18.7      39
2    19.1      41
3    19.7      38
4    21.5      45
5    21.7      41
6    21.8      52
7    22.0      44
8    23.4      44
9    23.8      49

1. 물고기 데이터에서 length와 weight 간의 공분산을 구하시오.

In [43]:
np.cov(data.length, data.weight)

array([[ 3.64622222,  7.67333333],
       [ 7.67333333, 28.01111111]])

In [45]:
data.cov()

length     weight
length  3.646222   7.673333
weight  7.673333  28.011111

2. 물고기 데이터에서  length와 weight 간의 상관계수를 구하시오.

In [46]:
np.corrcoef(data.length, data.weight)

array([[1.       , 0.7592719],
       [0.7592719, 1.       ]])

In [47]:
data.corr()

length    weight
length  1.000000  0.759272
weight  0.759272  1.000000

# 06.실습



1. 10개의 제비중에 4개의 당첨 제비가 포함되어 있다. 이 중 3개의 제비를 임의로 뽑을 때 다음을 구하시오.

    1) 3개 모두가 당첨 제비가 아닐 확률은?  
    2) 적어도 1개 이상이 제비일 확률은?

In [15]:
from itertools import combinations

lottery = list(combinations([1,1,1,1,0,0,0,0,0,0], 3))
N = len(list(lottery))

In [16]:
lottery

[(1, 1, 1),
 (1, 1, 1),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 1),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 1, 1),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 1, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1, 0, 0),
 (1,

In [46]:
wins = 0

for i in lottery:
    if (i.count(0) == 3):
        wins += 1

print('3개 모두가 당첨 제비가 아닐 확률 = ', wins/N)

3개 모두가 당첨 제비가 아닐 확률 =  0.16666666666666666


In [45]:
wins = 0

for i in lottery:
    if (i.count(1) == 1) or (i.count(1) == 2) or (i.count(1) == 3):
        wins += 1

print('적어도 1개 이상이 제비일 확률 = ', wins/N)

적어도 1개 이상이 제비일 확률 =  0.8333333333333334


In [43]:
1-(20/120)

0.8333333333333334

# 07 실습

1. 조건부 확률을 이용하여 다음 확률을 계산해 보자.  
백만명($10^6$)당 5명 꼴로 어떤 질병에 걸린다.  이 병의 진단 키트는 99.99%의 민감도로 질병을 판단한다.(0.01%의 확률로 잘못 판정한다.) A라는 사람이 이 검사에서 양성으로 나왔다면 실제로 이 사람이 이 질병에 걸렸을 확률은 얼마인가?

In [ ]:
p_병 = 0.000005

p_가능도 = 0.9999 # 진단 키트의 민감도

# p_양성 ==> 병 유무와 관계없이 양성이 나올 확률
# p_양성 = 병에 걸려서 양성 + 병에 안걸렸는데 양성
p_양성 = 0.000005 * 0.9999 + (1-0.000005)*0.0001

p_병_양성 = (0.9999 * 0.000005) / p_양성

p_병_양성


# 10실습

1. 복권의 당첨률이 30% 라고 한다. 복권을 8장 구입했다. 이항분포로 다음의 확률을 구하시오.
    - 4장이 당첨될 확률은? ($P=4$)
    - 3장에서 7장 당첨될 확률은? ( $P(3\le X \le 7$ )
    - 6장 이상 당첨될 확률은? ( $P \ge 6$ )

In [38]:
rv = stats.binom(8, 0.3)
rv.pmf(4), rv.cdf(7)-rv.cdf(2), 1-rv.cdf(5)

(0.1361367, 0.44816058000000014, 0.011292210000000025)

# 11실습

1. 확률변수 X가 평균이 70, 표준편차가 10인 정규분포를 따를때 다음의 확률을 구하시오.
    
    - P(X < 94.3)
    - P(X > 57.5)
    - P(57.7 < X < 94.3)

In [35]:
rv = stats.norm(loc = 70, scale=10)

rv.cdf(94.3), 1-rv.cdf(57.5), rv.cdf(94.3)-rv.cdf(57.5)

(0.9924505885836908, 0.8943502263331446, 0.8868008149168355)

# 14실습

1. 다음과 같은 물고기 10마리의 크기에 대한 표본 데이터가 있다. 

    - 물고기 크기의 표본평균과 분산, 표준편차를 구하시오.
    - 물고기 크기의 모평균의 점추정값을 구하시오.
    - 물고기 크기의 모평균에 대하여 신뢰수준 95% 신뢰구간을 구하시오.
    
    
```
data = pd.Series([4.353, 3.735, 5.945, 3.798, 4.088, 5.266, 3.273, 3.527, 4.15 ,3.736])

data
```

In [15]:
data = pd.Series([4.353, 3.735, 5.945, 3.798, 4.088, 5.266, 3.273, 3.527, 4.15 ,3.736])

data

0    4.353
1    3.735
2    5.945
3    3.798
4    4.088
5    5.266
6    3.273
7    3.527
8    4.150
9    3.736
dtype: float64

In [19]:
data.mean(), data.var(), data.std()

(4.187099999999999, 0.6803947666666669, 0.8248604528443989)

In [20]:
data.mean()

4.187099999999999

In [29]:
import numpy as np
n = len(data)
s_mean = data.mean()
u_var = data.var(ddof=1)
stats.t.interval(alpha=0.95, df=n-1, loc=s_mean, scale=np.sqrt(u_var/n))

(3.5970303786105924, 4.777169621389406)

# 15실습

1. 다음과 같은 과자 무게 데이터가 있다.

    * 과자 무게의 평균을 구하시오.
    * "과자의 평균 무게는 50g이다"라는 귀무가설을 유의수준 5%에서 검정하시오.(stats.ttest_1samp 함수를 사용하시오)

```
data = pd.Series([58.53 , 52.353, 74.446, 52.983, 55.877, 67.66 , 47.726, 50.267,
       56.501, 52.361, 45.458, 53.361, 52.129, 59.828, 41.682, 49.399,
       64.211, 69.859, 42.911, 60.159])
       
data
```

    

In [12]:
data = pd.Series([58.53 , 52.353, 74.446, 52.983, 55.877, 67.66 , 47.726, 50.267,
       56.501, 52.361, 45.458, 53.361, 52.129, 59.828, 41.682, 49.399,
       64.211, 69.859, 42.911, 60.159])

data


0     58.530
1     52.353
2     74.446
3     52.983
4     55.877
5     67.660
6     47.726
7     50.267
8     56.501
9     52.361
10    45.458
11    53.361
12    52.129
13    59.828
14    41.682
15    49.399
16    64.211
17    69.859
18    42.911
19    60.159
dtype: float64

In [13]:
data.mean()

55.385050000000014

In [14]:
stats.ttest_1samp(data, 50)

Ttest_1sampResult(statistic=2.7503924976265512, pvalue=0.01272413288213529)

# 16실습

1. 다음과 같은 데이터가 있다. 특정약을 복용하기 전/후의 체온이 차이가 있는지 검정해 보자.

```
data = pd.DataFrame({'medicine':['before', 'before', 'before', 'before', 'before', 'after', 'after','after', 'after', 'after'],
                     'body_temperature':[36.2, 36.2, 35.3, 36.1, 36.1, 36.8, 36.1, 36.8, 37.1, 36.9]})
                 
data                 
```


In [9]:
data = pd.DataFrame({'medicine':['before', 'before', 'before', 'before', 'before', 'after', 'after','after', 'after', 'after'],
                     'body_temperature':[36.2, 36.2, 35.3, 36.1, 36.1, 36.8, 36.1, 36.8, 37.1, 36.9]})

data

medicine  body_temperature
0   before              36.2
1   before              36.2
2   before              35.3
3   before              36.1
4   before              36.1
5    after              36.8
6    after              36.1
7    after              36.8
8    after              37.1
9    after              36.9

In [11]:
before = data[data.medicine=='before'].body_temperature
after = data[data.medicine=='after'].body_temperature

stats.ttest_rel(after, before)

Ttest_relResult(statistic=2.901693483620596, pvalue=0.044043109730074276)

# 17.실습

1. 다음과 같은 데이터가 있다. 버튼의 클릭률이 버튼색에 따라 달라지는지 검정해 보자. 

```
data = pd.DataFrame({'color':['blue', 'blue', 'red', 'red'],
                     'click':['click', 'not', 'click', 'not'],
                     'freq':[ 20, 230,  10,  40]})
data             
```

- pd.crosstab()을 사용하여 교차표를 만드시오.
- scipy.stats.chi2_countigency 함수를 사용하여 카이제곱 검정을 시행하시오.

In [1]:
from scipy import stats

In [2]:
import pandas as pd

data = pd.DataFrame({'color':['blue', 'blue', 'red', 'red'],
                     'click':['click', 'not', 'click', 'not'],
                     'freq':[ 20, 230,  10,  40]})
data             



color  click  freq
0  blue  click    20
1  blue    not   230
2   red  click    10
3   red    not    40

In [3]:
cross = pd.crosstab(data.color,data.click,data.freq, aggfunc='sum')

In [6]:
cross

click  click  not
color            
blue      20  230
red       10   40

In [7]:
from scipy import stats

stats.chi2_contingency(cross, correction=False)

(6.666666666666666,
 0.009823274507519247,
 1,
 array([[ 25., 225.],
        [  5.,  45.]]))