# Making Predictions with the Standardized Coefficients

## Import the relevant libraries

In [1]:
# For these lessons we will need NumPy, pandas, matplotlib and seaborn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# and of course the actual regression (machine learning) module
from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
# Load the data from a .csv in the same folder
data = pd.read_csv('../../data/1.02. Multiple linear regression.csv')

# Let's explore the top 5 rows of the df
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Create the multiple linear regression

### Declare the dependent and independent variables

In [4]:
# There are two independent variables: 'SAT' and 'Rand 1,2,3'
x = data[['SAT','Rand 1,2,3']]

# and a single dependent variable: 'GPA'
y = data['GPA']

## Standardization

스케일이 서로 다른 변수를 사용할 때는 표준화함으로 데이터의 스케일을 맞춘다.  
이렇게 변수를 표준화하면 단일한 척도로 변환할 수 있다.

**표준화 계수란?** 
단위와 분포의 평균이 변수마다 다르기 때문에 이를 비교해보기 위해서 변환한 수치를 의미한다.  
다음의 공식으로 표준화 한다.  

$ z = \frac{X - \mu}{\sigma}$

In [5]:
# Import the preprocessing module
# StandardScaler 모듈을 사용하여 표준화를 수행한다.
from sklearn.preprocessing import StandardScaler

In [6]:
# Create an instance of the StandardScaler class
scaler = StandardScaler()

In [7]:
# Fit the input data (x)
# 각각의 feature(독립변수)별로 표준화된 계수를 계산한다.
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
# 'transform()'메소드를 사용하여 data를 표준화한다. 

# The actual scaling of the data is done through the method '
# Let's store it in a new variable, named appropriately
x_scaled = scaler.transform(x)

In [9]:
# The result is an ndarray
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

## Regression with scaled features

표준화된 데이터를 사용하여 회귀모형을 생성한다.

In [10]:
# Creating a regression works in the exact same way
reg = LinearRegression()

# We just need to specify that our inputs are the 'scaled inputs'
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
# Let's see the coefficients
reg.coef_

array([ 0.17181389, -0.00703007])

In [12]:
# And the intercept
reg.intercept_

3.330238095238095

## Creating a summary table

**회귀결과를 요약하는 summary table을 생성해 보자.**

In [13]:
# Let's create a new data frame with the names of the features
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])

# 'Weights' 는 회귀식에서 회귀계수를 의미한다.
# 보통 머신러닝에서는 회귀계수보다는 weight라는 표현을 더 많이 사용한다.

reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [14]:
# Now we have a pretty clean summary, which can help us make an informed decision about the importance of each feature
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

## Making predictions with the standardized coefficients (weights)

표준화된 계수로 생성된 회귀모형으로 예측을 수행한다.

In [15]:
# For simplicity, let's crete a new dataframe with 2 *new* observations
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [16]:
# We can make a prediction for a whole dataframe (not a single value)
# Note that the output is very strange (different from mine)
reg.predict(new_data)

array([295.39979563, 312.58821497])

우리의 모형은 표준화된 feature를 사용한다.  
따라서 새로운 데이터로 예측을 수행하기 위해서는 동일하게 표준화된 값으로 예측을 수행해야 한다.  


In [17]:
new_data_scaled = scaler.transform(new_data)

# Let's check the result
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [18]:
# Finally we make a prediction using the scaled new data
reg.predict(new_data_scaled)
# The output is much more appropriate, isn't it?

array([3.09051403, 3.26413803])

## What if we removed the 'Random 1,2,3' variable?

표준화된 회귀모형에서 **'Random 1,2,3'의 회귀계수는 매우 작다.**   

이것은 해당 모형에서 **'Random 1,2,3'이라는 변수의 영향력이 매우 작다**는 뜻이다.   
'Random 1,2,3'이라는 변수를 제거하면 어떻게 될까? 

In [19]:
# Theory suggests that features with very small weights could be removed and the results should be identical
# Moreover, we proved in 2-3 different ways that 'Rand 1,2,3' is an irrelevant feature
# Let's create a simple linear regression (simple, because there is a single feature) without 'Rand 1,2,3'
reg_simple = LinearRegression()

# Once more, we must reshape the inputs into a matrix, otherwise we will get a compatibility error 
# Note that instead of standardizing again, I'll simply take only the first column of x
x_simple_matrix = x_scaled[:,0].reshape(-1,1)

# Finally, we fit the regression
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
# In a similar manner to the cell before, we can predict only the first column of the scaled 'new data'
# Note that we also reshape it to be exactly the same as x
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

모형에서 영향력이 매우 작은 'Random 1,2,3'를 제거해도 회귀식의 예측에는 큰 변화가 없다.  
>**오컴의 면도날(Occam's Razor 또는 Ockham's Razor)**   
흔히 '경제성의 원리' (Principle of economy), 검약의 원리(lex parsimoniae), 또는 **단순성의 원리**라고도 한다.  
즉 회귀식에서도 불필요한 변수를 제거하여 단순한 모형을 생성하는 것이 더 좋은 모형을 생성하는 방법이다.