# 결측치 처리하기

* 결측치란? 어떤 이유로 값이 없는 데이터를 말한다.
* 결측치 처리 방법
    * 데이터가 NaN일 때 그대로 삭제한다. (complete drop)
    * 데이터가 거의 없는 feature는 feature 자체를 삭제한다.
    * 최빈값, 평균값 등 특정값으로 NaN을 대체 한다.(imputation)


## 결측치 다루기
테이블 형태 데이터에서 누락된 값 식별하기

In [1]:
import pandas as pd
from io import StringIO

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [3]:
df.isnull().sum()# 결측치의 갯수

A    0
B    0
C    1
D    1
dtype: int64

In [ ]:
# `values` 속성으로 넘파이 배열을 얻을 수 있습니다.
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### 누락된 값이 있는 샘플이나 특성을 제외하기

In [ ]:
# 누락된 값이 있는 행을 삭제합니다.

df.dropna(axis=0) #기본

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
# 누락된 값이 있는 열을 삭제합니다.

df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [ ]:
# 모든 열이 NaN일 때만 행을 삭제합니다.

df.dropna(how='all')  

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [ ]:
# 실수 값이 4개보다 작은 행을 삭제합니다

df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [ ]:
# 특정 열에 NaN이 있는 행만 삭제합니다(여기서는 ‘C’열).

df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

### 누락된 값을 대체하기

In [ ]:
# 원본 배열
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [5]:
# fill_na()로 결측치 대체하기
df.fillna(-99)

A     B     C     D
0   1.0   2.0   3.0   4.0
1   5.0   6.0 -99.0   8.0
2  10.0  11.0  12.0 -99.0

### 사이킷런 imputer 사용하여 결측값 대체하기

**Version 차이**
* sklearn 0.23 이상에서는 SimpleImputer를 사용한다.
* 그 이하 버전에서는 SimpleImputer를 사용하는 대신에 Imputer를 사용해야 한다.
* 옵션 등에 차이가 있다.

In [ ]:
# sklearn 0.19 버전에서 이 코드를 사용한다. 
# 0.23 이상에서 에러남

import numpy as np
from sklearn.preprocessing import Imputer

simr = Imputer(missing_values=np.nan, strategy='mean')
simr = simr.fit(df.values)
imputed_data = simr.transform(df.values)
imputed_data

In [8]:
import numpy as np
x = [ [np.nan, 2, 3], 
        [4, np.nan, 6], 
        [10, np.nan, 9] ]

from sklearn.impute import SimpleImputer

simr = SimpleImputer(missing_values=np.nan, strategy='mean')
simr = simr.fit_transform(x)
simr

array([[ 7.,  2.,  3.],
       [ 4.,  2.,  6.],
       [10.,  2.,  9.]])

In [ ]:
#  sklearn 0.23 이상에서는 이 코드를 사용하여 결측치를 대체한다.

import numpy as np
from sklearn.impute import SimpleImputer

simr = SimpleImputer(missing_values=np.nan, strategy='mean')
simr = simr.fit(df.values)
imputed_data = simr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])